export const DINOS: any[] = [
  {
    name: "Allosaurus",
    rarity: "0",
    hp: "4500",
    armor: "0",
    damage: "1650",
    crit: "20",
    speed: "104",
    move1: "Defense Shattering Strike",
    move2: "Armor Piercing Impact",
    move3: "",
    move4: "",
    passive: "",
    filename: "Allosauru"
  },
  {
    name: "Allosinosaurus",
    rarity: "3",
    hp: "4500",
    armor: "15",
    damage: "1420",
    crit: "20",
    speed: "106",
    move1: "Armor Piercing Strike",
    move2: "Armor Piercing Impact",
    move3: "Armor Piercing Rampage",
    move4: "Instant Charge",
    passive: "",
    filename: "Allosinos",
    ing1: "Allosaurus",
    ing2: "Sinoceratops"
  },
  {
    name: "Amargasaurus",
    rarity: "1",
    hp: "5310",
    armor: "0",
    damage: "1060",
    crit: "5",
    speed: "103",
    move1: "Strike",
    move2: "Decelerating Impact",
    move3: "Slowing Impact",
    move4: "",
    passive: "",
    filename: "Amargasau"
  },
  {
    name: "Amargocephalus",
    rarity: "2",
    hp: "4290",
    armor: "40",
    damage: "850",
    crit: "5",
    speed: "104",
    move1: "Vulnerability Strike",
    move2: "Impact",
    move3: "Instant Invencibility",
    move4: "Decelerating Impact",
    passive: "Counter05",
    filename: "Amargocep",
    ing1: "Amargasaurus",
    ing2: "Euoplocephalus"
  },
  {
    name: "Ankylocodon",
    rarity: "1",
    hp: "3900",
    armor: "25",
    damage: "800",
    crit: "20",
    speed: "107",
    move1: "Armor Piercing Strike",
    move2: "Armor Piercing Impact",
    move3: "Decelerating Impact",
    move4: "Short Defense",
    passive: "Immune",
    filename: "Ankylocod",
    ing1: "Ankylosaurus Gen 2",
    ing2: "Ophiacodon"
  },
  {
    name: "Ankylosaurus",
    rarity: "2",
    hp: "4800",
    armor: "30",
    damage: "980",
    crit: "5",
    speed: "116",
    move1: "Vulnerability Strike",
    move2: "Long Protection",
    move3: "Instant Invencibility",
    move4: "",
    passive: "",
    filename: "Ankylosau"
  },
  {
    name: "Ankylosaurus Gen 2",
    rarity: "0",
    hp: "4710",
    armor: "25",
    damage: "1000",
    crit: "5",
    speed: "112",
    move1: "Vulnerability Strike",
    move2: "Long Protection",
    move3: "",
    move4: "",
    passive: "",
    filename: "Ankylosau2"
  },
  {
    name: "Ankyntrosaurus",
    rarity: "3",
    hp: "4710",
    armor: "30",
    damage: "1000",
    crit: "5",
    speed: "115",
    move1: "Nullifying Strike",
    move2: "Thagomizer",
    move3: "Instant Invencibility",
    move4: "Instant Cripple",
    passive: "Counter05",
    filename: "Ankyntros",
    ing1: "Ankylosaurus",
    ing2: "Kentrosaurus"
  },
  {
    name: "Apatosaurus",
    rarity: "0",
    hp: "6600",
    armor: "0",
    damage: "820",
    crit: "5",
    speed: "101",
    move1: "Strike",
    move2: "Decelerating Impact",
    move3: "",
    move4: "",
    passive: "",
    filename: "Apatosaur"
  },
  {
    name: "Argentinosaurus",
    rarity: "1",
    hp: "5100",
    armor: "0",
    damage: "1050",
    crit: "40",
    speed: "102",
    move1: "Strike",
    move2: "Decelerating Impact",
    move3: "Impact",
    move4: "",
    passive: "",
    filename: "Argentino"
  },
  {
    name: "Baryonyx",
    rarity: "2",
    hp: "3750",
    armor: "0",
    damage: "1300",
    crit: "20",
    speed: "124",
    move1: "Armor Piercing Strike",
    move2: "Ready to Crush",
    move3: "Defense Shattering Rampage",
    move4: "",
    passive: "",
    filename: "Baryonyx"
  },
  {
    name: "Baryonyx Gen 2",
    rarity: "1",
    hp: "3900",
    armor: "0",
    damage: "1240",
    crit: "20",
    speed: "123",
    move1: "Armor Piercing Strike",
    move2: "Ready to Crush",
    move3: "Defense Shattering Impact",
    move4: "",
    passive: "",
    filename: "Baryonyx2"
  },
  {
    name: "Blue",
    rarity: "2",
    hp: "3000",
    armor: "10",
    damage: "1150",
    crit: "5",
    speed: "131",
    move1: "Strike",
    move2: "Pounce",
    move3: "Short Defense",
    move4: "",
    passive: "",
    filename: "Blue"
  },
  {
    name: "Brachiosaurus",
    rarity: "2",
    hp: "6000",
    armor: "10",
    damage: "1050",
    crit: "5",
    speed: "111",
    move1: "Superiority Strike",
    move2: "Surprise Bellow",
    move3: "Rampage",
    move4: "",
    passive: "",
    filename: "Brachiosa"
  },
  {
    name: "Carnotaurus",
    rarity: "1",
    hp: "4050",
    armor: "0",
    damage: "900",
    crit: "5",
    speed: "104",
    move1: "Vulnerability Strike",
    move2: "Short Defense",
    move3: "Cleansing Impact",
    move4: "",
    passive: "Counter",
    filename: "Carnotaur"
  },
  {
    name: "Charlie",
    rarity: "1",
    hp: "2100",
    armor: "0",
    damage: "1380",
    crit: "5",
    speed: "129",
    move1: "Strike",
    move2: "Pounce",
    move3: "Critical Impact",
    move4: "",
    passive: "",
    filename: "Charlie"
  },
  {
    name: "Concavenator",
    rarity: "2",
    hp: "3690",
    armor: "0",
    damage: "1050",
    crit: "5",
    speed: "106",
    move1: "Pinning Strike",
    move2: "Short Defense",
    move3: "Armor Piercing Impact",
    move4: "",
    passive: "Counter",
    filename: "Concavena"
  },
  {
    name: "Deinocheirus",
    rarity: "0",
    hp: "3000",
    armor: "0",
    damage: "1280",
    crit: "5",
    speed: "130",
    move1: "Minimal Speedup Strike",
    move2: "Rampage",
    move3: "",
    move4: "",
    passive: "",
    filename: "Deinochei"
  },
  {
    name: "Delta",
    rarity: "1",
    hp: "2400",
    armor: "0",
    damage: "1300",
    crit: "5",
    speed: "131",
    move1: "Strike",
    move2: "Pounce",
    move3: "Impact and Run",
    move4: "",
    passive: "",
    filename: "Delta"
  },
  {
    name: "Dilophosaurus",
    rarity: "1",
    hp: "3750",
    armor: "0",
    damage: "1150",
    crit: "5",
    speed: "124",
    move1: "Nullifying Strike",
    move2: "Distracting Strike",
    move3: "Nullifying Impact",
    move4: "",
    passive: "",
    filename: "Dilophosa"
  },
  {
    name: "Dilophosaurus Gen 2",
    rarity: "0",
    hp: "3000",
    armor: "0",
    damage: "1320",
    crit: "5",
    speed: "121",
    move1: "Nullifying Strike",
    move2: "Distracting Impact",
    move3: "",
    move4: "",
    passive: "",
    filename: "Dilophosa2"
  },
  {
    name: "Diloranosaurus",
    rarity: "3",
    hp: "4200",
    armor: "0",
    damage: "1400",
    crit: "5",
    speed: "126",
    move1: "Superiority Strike",
    move2: "Distracting Impact",
    move3: "Greater Stunning Rampage",
    move4: "Impact and Run",
    passive: "",
    filename: "Diloranos",
    ing1: "Dilophosaurus",
    ing2: "Ouranosaurus"
  },
  {
    name: "Dimetrodon",
    rarity: "1",
    hp: "4200",
    armor: "0",
    damage: "1000",
    crit: "5",
    speed: "113",
    move1: "Defense Shattering Strike",
    move2: "Defense Shattering Impact",
    move3: "Critical Impact",
    move4: "",
    passive: "Immune",
    filename: "Dimetrodo"
  },
  {
    name: "Dimetrodon Gen 2",
    rarity: "0",
    hp: "4200",
    armor: "0",
    damage: "1000",
    crit: "5",
    speed: "112",
    move1: "Defense Shattering Strike",
    move2: "Armor Piercing Rampage",
    move3: "",
    move4: "",
    passive: "Immune",
    filename: "Dimetrodo2"
  },
  {
    name: "Diorajasaur",
    rarity: "4",
    hp: "4200",
    armor: "30",
    damage: "1000",
    crit: "5",
    speed: "108",
    move1: "Pinning Strike",
    move2: "Short Defense",
    move3: "Distracting Impact",
    move4: "Instant Invencibility",
    passive: "Counter",
    filename: "Tuorajaky",
    ing1: "Rajakylosaurus",
    ing2: "Tuojiangosaurus"
  },
  {
    name: "Diplocaulus",
    rarity: "0",
    hp: "3000",
    armor: "0",
    damage: "1250",
    crit: "5",
    speed: "124",
    move1: "Nullifying Strike",
    move2: "Distracting Impact",
    move3: "",
    move4: "",
    passive: "",
    filename: "Diplocaul"
  },
  {
    name: "Diplocaulus Gen 2",
    rarity: "1",
    hp: "4500",
    armor: "0",
    damage: "1130",
    crit: "5",
    speed: "122",
    move1: "Nullifying Strike",
    move2: "Distracting Impact",
    move3: "Instant Cripple",
    move4: "",
    passive: "",
    filename: "Diplocaul2"
  },
  {
    name: "Diplotator",
    rarity: "1",
    hp: "4800",
    armor: "0",
    damage: "1000",
    crit: "5",
    speed: "120",
    move1: "Defense Shattering Strike",
    move2: "Ferocious Strike",
    move3: "Distracting Strike",
    move4: "Defense Shattering Impact",
    passive: "",
    filename: "Diplotato",
    ing1: "Diplocaulus",
    ing2: "Irritator Gen 2"
  },
  {
    name: "Dracorex",
    rarity: "1",
    hp: "3720",
    armor: "0",
    damage: "1220",
    crit: "5",
    speed: "124",
    move1: "Minor Stunning Strike",
    move2: "Strike And Run",
    move3: "Instant Charge",
    move4: "",
    passive: "",
    filename: "Dracorex"
  },
  {
    name: "Dracorex Gen 2",
    rarity: "0",
    hp: "3990",
    armor: "0",
    damage: "1200",
    crit: "5",
    speed: "119",
    move1: "Strike",
    move2: "Strike And Run",
    move3: "",
    move4: "",
    passive: "",
    filename: "Dracorex2"
  },
  {
    name: "Echo",
    rarity: "1",
    hp: "2490",
    armor: "0",
    damage: "1370",
    crit: "5",
    speed: "126",
    move1: "Strike",
    move2: "Pounce",
    move3: "Cleansing Impact",
    move4: "",
    passive: "",
    filename: "Echo"
  },
  {
    name: "Edmontosaurus",
    rarity: "1",
    hp: "4920",
    armor: "0",
    damage: "1020",
    crit: "5",
    speed: "109",
    move1: "Superiority Strike",
    move2: "Greater Stunning Strike",
    move3: "Strike And Run",
    move4: "",
    passive: "",
    filename: "Edmontosa"
  },
  {
    name: "Einiasuchus",
    rarity: "1",
    hp: "3660",
    armor: "20",
    damage: "1300",
    crit: "5",
    speed: "117",
    move1: "Minimal Stunning Strike",
    move2: "Stunning Impact",
    move3: "Adrenaline Pulse",
    move4: "Ferocious Strike",
    passive: "",
    filename: "Einiasuch",
    ing1: "Einiosaurus",
    ing2: "Nundasuchus"
  },
  {
    name: "Einiosaurus",
    rarity: "0",
    hp: "4440",
    armor: "15",
    damage: "1300",
    crit: "5",
    speed: "114",
    move1: "Minimal Stunning Strike",
    move2: "Stunning Impact",
    move3: "",
    move4: "",
    passive: "",
    filename: "Einiosaur"
  },
  {
    name: "Erlidominus",
    rarity: "4",
    hp: "3000",
    armor: "0",
    damage: "1400",
    crit: "20",
    speed: "125",
    move1: "Minimal Speedup Strike",
    move2: "Rampage",
    move3: "Strike And Run",
    move4: "Cloak",
    passive: "Immune",
    filename: "Erlikomin",
    ing1: "Erlikosaurus",
    ing2: "Indominus Rex"
  },
  {
    name: "Erlikosaurus",
    rarity: "2",
    hp: "3090",
    armor: "0",
    damage: "1400",
    crit: "5",
    speed: "128",
    move1: "Minimal Speedup Strike",
    move2: "Rampage",
    move3: "Strike And Run",
    move4: "",
    passive: "",
    filename: "Erlikosau"
  },
  {
    name: "Erlikosaurus Gen 2",
    rarity: "1",
    hp: "2850",
    armor: "0",
    damage: "1280",
    crit: "5",
    speed: "129",
    move1: "Minimal Speedup Strike",
    move2: "Rampage",
    move3: "Debilitating Distraction",
    move4: "",
    passive: "",
    filename: "Erlikosau2"
  },
  {
    name: "Euoplocephalus",
    rarity: "0",
    hp: "4500",
    armor: "40",
    damage: "950",
    crit: "5",
    speed: "112",
    move1: "Vulnerability Strike",
    move2: "Impact",
    move3: "",
    move4: "",
    passive: "",
    filename: "Euoplocep"
  },
  {
    name: "Gallimimus",
    rarity: "0",
    hp: "1950",
    armor: "0",
    damage: "1200",
    crit: "5",
    speed: "124",
    move1: "Evasive Strike",
    move2: "Impact and Run",
    move3: "",
    move4: "",
    passive: "Immune",
    filename: "Gallimimu"
  },
  {
    name: "Gigaspikasaur",
    rarity: "3",
    hp: "4800",
    armor: "40",
    damage: "850",
    crit: "5",
    speed: "107",
    move1: "Lockdown Strike",
    move2: "Decelerating Impact",
    move3: "Short Defense",
    move4: "Armor Piercing Impact",
    passive: "Counter05",
    filename: "Amargadop",
    ing1: "Amargasaurus",
    ing2: "Nodopatosaurus"
  },
  {
    name: "Giraffatitan",
    rarity: "1",
    hp: "5760",
    armor: "10",
    damage: "1000",
    crit: "10",
    speed: "107",
    move1: "Superiority Strike",
    move2: "Surprise Bellow",
    move3: "Rampage",
    move4: "",
    passive: "",
    filename: "Giraffati"
  },
  {
    name: "Gorgosaurus",
    rarity: "1",
    hp: "3900",
    armor: "0",
    damage: "1550",
    crit: "20",
    speed: "102",
    move1: "Defense Shattering Strike",
    move2: "Defense Shattering Impact",
    move3: "Ferocious Strike",
    move4: "",
    passive: "",
    filename: "Gorgosaur"
  },
  {
    name: "Gorgosuchus",
    rarity: "2",
    hp: "3600",
    armor: "0",
    damage: "1360",
    crit: "20",
    speed: "120",
    move1: "Defense Shattering Strike",
    move2: "Ferocious Strike",
    move3: "Defense Shattering Rampage",
    move4: "Adrenaline Surge",
    passive: "",
    filename: "Gorgosuch",
    ing1: "Gorgosaurus",
    ing2: "Kaprosuchus"
  },
  {
    name: "Gryposuchus",
    rarity: "2",
    hp: "4200",
    armor: "20",
    damage: "1000",
    crit: "20",
    speed: "116",
    move1: "Vulnerability Strike",
    move2: "Lockdown Impact",
    move3: "Ferocious Strike",
    move4: "",
    passive: "",
    filename: "Gryposuch"
  },
  {
    name: "Iguanodon",
    rarity: "0",
    hp: "4920",
    armor: "0",
    damage: "1050",
    crit: "5",
    speed: "114",
    move1: "Superiority Strike",
    move2: "Greater Stunning Strike",
    move3: "",
    move4: "",
    passive: "",
    filename: "Iguanodon"
  },
  {
    name: "Indominus Rex",
    rarity: "3",
    hp: "4200",
    armor: "0",
    damage: "1200",
    crit: "20",
    speed: "107",
    move1: "Armor Piercing Strike",
    move2: "Armor Piercing Impact",
    move3: "Armor Piercing Rampage",
    move4: "Cloak",
    passive: "Immune",
    filename: "Indominus",
    ing1: "Velociraptor",
    ing2: "Tyrannosaurus Rex"
  },
  {
    name: "Indoraptor",
    rarity: "4",
    hp: "3750",
    armor: "0",
    damage: "1400",
    crit: "20",
    speed: "128",
    move1: "Armor Piercing Strike",
    move2: "Cleansing Impact",
    move3: "Defense Shattering Rampage",
    move4: "Evasive Stance",
    passive: "",
    filename: "Indorapto",
    ing1: "Velociraptor",
    ing2: "Indominus Rex"
  },
  {
    name: "Irritator",
    rarity: "1",
    hp: "4800",
    armor: "0",
    damage: "1030",
    crit: "5",
    speed: "123",
    move1: "Defense Shattering Strike",
    move2: "Ready to Crush",
    move3: "Defense Shattering Impact",
    move4: "",
    passive: "",
    filename: "Irritator"
  },
  {
    name: "Irritator Gen 2",
    rarity: "0",
    hp: "4650",
    armor: "0",
    damage: "1000",
    crit: "20",
    speed: "124",
    move1: "Defense Shattering Strike",
    move2: "Ready to Crush",
    move3: "",
    move4: "",
    passive: "",
    filename: "Irritator2"
  },
  {
    name: "Kaprosuchus",
    rarity: "1",
    hp: "4500",
    armor: "0",
    damage: "1000",
    crit: "5",
    speed: "123",
    move1: "Defense Shattering Strike",
    move2: "Ferocious Impact",
    move3: "Cleansing Impact",
    move4: "",
    passive: "",
    filename: "Kaprosuch"
  },
  {
    name: "Kentrosaurus",
    rarity: "2",
    hp: "4050",
    armor: "0",
    damage: "1210",
    crit: "5",
    speed: "120",
    move1: "Superiority Strike",
    move2: "Thagomizer",
    move3: "Instant Cripple",
    move4: "",
    passive: "Counter05",
    filename: "Kentrosau"
  },
  {
    name: "Koolasuchus",
    rarity: "2",
    hp: "4500",
    armor: "0",
    damage: "1000",
    crit: "5",
    speed: "123",
    move1: "Nullifying Strike",
    move2: "Distracting Impact",
    move3: "Slowing Impact",
    move4: "",
    passive: "",
    filename: "Koolasuch"
  },
  {
    name: "Koolasuchus Gen 2",
    rarity: "1",
    hp: "4290",
    armor: "0",
    damage: "1500",
    crit: "5",
    speed: "120",
    move1: "Nullifying Strike",
    move2: "Distracting Strike",
    move3: "Instant Cripple",
    move4: "",
    passive: "",
    filename: "Koolasuch2"
  },
  {
    name: "Lythronax",
    rarity: "0",
    hp: "4050",
    armor: "0",
    damage: "890",
    crit: "5",
    speed: "104",
    move1: "Pinning Strike",
    move2: "Long Protection",
    move3: "",
    move4: "",
    passive: "Counter",
    filename: "Lythronax"
  },
  {
    name: "Magnapyritor",
    rarity: "4",
    hp: "3000",
    armor: "0",
    damage: "1400",
    crit: "20",
    speed: "128",
    move1: "Armor Piercing Strike",
    move2: "Nullifying Impact",
    move3: "Expose Weak Spot",
    move4: "Defense Shattering Rampage",
    passive: "Immune",
    filename: "Dimepyrri",
    ing1: "Dimetrodon",
    ing2: "Pyrritator"
  },
  {
    name: "Majundasuchus",
    rarity: "1",
    hp: "3360",
    armor: "0",
    damage: "900",
    crit: "5",
    speed: "108",
    move1: "Pinning Strike",
    move2: "Short Defense",
    move3: "Ferocious Strike",
    move4: "Cleansing Impact",
    passive: "Counter",
    filename: "Majundasu",
    ing1: "Majungasaurus",
    ing2: "Nundasuchus"
  },
  {
    name: "Majungasaurus",
    rarity: "0",
    hp: "3930",
    armor: "0",
    damage: "860",
    crit: "5",
    speed: "105",
    move1: "Pinning Strike",
    move2: "Short Defense",
    move3: "",
    move4: "",
    passive: "Counter",
    filename: "Majungasa"
  },
  {
    name: "Megalosaurus",
    rarity: "1",
    hp: "4050",
    armor: "0",
    damage: "950",
    crit: "5",
    speed: "105",
    move1: "Pinning Strike",
    move2: "Short Defense",
    move3: "Impact",
    move4: "",
    passive: "Counter",
    filename: "Megalosau"
  },
  {
    name: "Megalosuchus",
    rarity: "3",
    hp: "4500",
    armor: "0",
    damage: "1000",
    crit: "5",
    speed: "115",
    move1: "Pinning Strike",
    move2: "Ferocious Strike",
    move3: "Critical Impact",
    move4: "Short Defense",
    passive: "Counter",
    filename: "Megalosuc",
    ing1: "Megalosaurus",
    ing2: "Gorgosuchus"
  },
  {
    name: "Monolophosaurus",
    rarity: "2",
    hp: "3000",
    armor: "0",
    damage: "1110",
    crit: "5",
    speed: "127",
    move1: "Nullifying Strike",
    move2: "Distracting Rampage",
    move3: "Distracting Strike",
    move4: "",
    passive: "",
    filename: "Monolopho"
  },
  {
    name: "Monolophosaurus Gen 2",
    rarity: "0",
    hp: "3000",
    armor: "0",
    damage: "1200",
    crit: "5",
    speed: "126",
    move1: "Nullifying Strike",
    move2: "Slowing Impact",
    move3: "",
    move4: "",
    passive: "",
    filename: "Monolopho2"
  },
  {
    name: "Monomimus",
    rarity: "3",
    hp: "3510",
    armor: "0",
    damage: "1230",
    crit: "5",
    speed: "129",
    move1: "Nullifying Strike",
    move2: "Nullifying Impact",
    move3: "Distracting Impact",
    move4: "Evasive Stance",
    passive: "Immune",
    filename: "Monomimus",
    ing1: "Gallimimus",
    ing2: "Monolophosaurus"
  },
  {
    name: "Monostegotops",
    rarity: "3",
    hp: "4200",
    armor: "30",
    damage: "1300",
    crit: "20",
    speed: "117",
    move1: "Nullifying Strike",
    move2: "Stunning Impact",
    move3: "Nullifying Impact",
    move4: "Slowing Impact",
    passive: "",
    filename: "Monostego",
    ing1: "Stegoceratops",
    ing2: "Monolophosaurus"
  },
  {
    name: "Nodopatosaurus",
    rarity: "2",
    hp: "4800",
    armor: "25",
    damage: "800",
    crit: "5",
    speed: "106",
    move1: "Pinning Strike",
    move2: "Decelerating Impact",
    move3: "Armor Piercing Impact",
    move4: "Short Defense",
    passive: "Counter05",
    filename: "Nodopatos",
    ing1: "Apatosaurus",
    ing2: "Nodosaurus"
  },
  {
    name: "Nodosaurus",
    rarity: "1",
    hp: "4500",
    armor: "25",
    damage: "1050",
    crit: "5",
    speed: "115",
    move1: "Vulnerability Strike",
    move2: "Armor Piercing Impact",
    move3: "Short Defense",
    move4: "",
    passive: "",
    filename: "Nodosauru"
  },
  {
    name: "Nundasuchus",
    rarity: "0",
    hp: "3000",
    armor: "0",
    damage: "1440",
    crit: "5",
    speed: "128",
    move1: "Strike",
    move2: "Ferocious Strike",
    move3: "",
    move4: "",
    passive: "",
    filename: "Nundasuch"
  },
  {
    name: "Ophiacodon",
    rarity: "0",
    hp: "4200",
    armor: "0",
    damage: "1100",
    crit: "40",
    speed: "107",
    move1: "Armor Piercing Strike",
    move2: "Armor Piercing Rampage",
    move3: "",
    move4: "",
    passive: "Immune",
    filename: "Ophiacodo"
  },
  {
    name: "Ornithomimus",
    rarity: "1",
    hp: "2820",
    armor: "0",
    damage: "1200",
    crit: "5",
    speed: "131",
    move1: "Evasive Strike",
    move2: "Impact and Run",
    move3: "Instant Cripple",
    move4: "",
    passive: "Immune",
    filename: "Ornithomi"
  },
  {
    name: "Ouranosaurus",
    rarity: "2",
    hp: "4830",
    armor: "0",
    damage: "1050",
    crit: "5",
    speed: "114",
    move1: "Superiority Strike",
    move2: "Greater Stunning Rampage",
    move3: "Impact and Run",
    move4: "",
    passive: "",
    filename: "Ouranosau"
  },
  {
    name: "Paramoloch",
    rarity: "3",
    hp: "4800",
    armor: "0",
    damage: "1000",
    crit: "5",
    speed: "121",
    move1: "Low Stunning Strike",
    move2: "Rampage and Run",
    move3: "Instant Charge",
    move4: "Greater Stunning Impact",
    passive: "",
    filename: "Paramoloc",
    ing1: "Parasaurolophus",
    ing2: "Stygimoloch"
  },
  {
    name: "Parasaurolophus",
    rarity: "0",
    hp: "4980",
    armor: "0",
    damage: "1050",
    crit: "5",
    speed: "113",
    move1: "Superiority Strike",
    move2: "Impact and Run",
    move3: "",
    move4: "",
    passive: "",
    filename: "Parasauro"
  },
  {
    name: "Postimetrodon",
    rarity: "2",
    hp: "4200",
    armor: "0",
    damage: "1000",
    crit: "5",
    speed: "124",
    move1: "Defense Shattering Strike",
    move2: "Ferocious Strike",
    move3: "Defense Shattering Impact",
    move4: "Adrenaline Surge",
    passive: "Immune",
    filename: "Postimetr",
    ing1: "Dimetrodon",
    ing2: "Postosuchus"
  },
  {
    name: "Postosuchus",
    rarity: "1",
    hp: "3600",
    armor: "0",
    damage: "1400",
    crit: "5",
    speed: "126",
    move1: "Defense Shattering Strike",
    move2: "Ferocious Impact",
    move3: "Adrenaline Pulse",
    move4: "",
    passive: "",
    filename: "Postosuch"
  },
  {
    name: "Proceratosaurus",
    rarity: "1",
    hp: "3000",
    armor: "0",
    damage: "1260",
    crit: "5",
    speed: "125",
    move1: "Nullifying Strike",
    move2: "Distracting Impact",
    move3: "Slowing Impact",
    move4: "",
    passive: "",
    filename: "Procerato"
  },
  {
    name: "Purussaurus",
    rarity: "1",
    hp: "4200",
    armor: "10",
    damage: "1000",
    crit: "5",
    speed: "112",
    move1: "Vulnerability Strike",
    move2: "Lockdown Impact",
    move3: "Ferocious Impact",
    move4: "",
    passive: "",
    filename: "Purussaur"
  },
  {
    name: "Purussaurus Gen 2",
    rarity: "0",
    hp: "3900",
    armor: "10",
    damage: "1000",
    crit: "20",
    speed: "111",
    move1: "Vulnerability Strike",
    move2: "Lockdown Impact",
    move3: "",
    move4: "",
    passive: "",
    filename: "Purussaur2"
  },
  {
    name: "Pyroraptor",
    rarity: "2",
    hp: "2520",
    armor: "0",
    damage: "1370",
    crit: "10",
    speed: "129",
    move1: "Strike",
    move2: "Pounce",
    move3: "Armor Piercing Impact",
    move4: "",
    passive: "",
    filename: "Pyrorapto"
  },
  {
    name: "Pyrritator",
    rarity: "3",
    hp: "3000",
    armor: "0",
    damage: "1350",
    crit: "5",
    speed: "128",
    move1: "Armor Piercing Strike",
    move2: "Distracting Rampage",
    move3: "Armor Piercing Rampage",
    move4: "Ready to Crush",
    passive: "",
    filename: "Pyrritato",
    ing1: "Pyroraptor",
    ing2: "Irritator"
  },
  {
    name: "Rajakylosaurus",
    rarity: "3",
    hp: "4800",
    armor: "30",
    damage: "890",
    crit: "5",
    speed: "104",
    move1: "Pinning Strike",
    move2: "Long Protection",
    move3: "Extended Critical Strike",
    move4: "Instant Invencibility",
    passive: "Counter",
    filename: "Rajakylos",
    ing1: "Rajasaurus",
    ing2: "Ankylosaurus"
  },
  {
    name: "Rajasaurus",
    rarity: "2",
    hp: "4110",
    armor: "0",
    damage: "910",
    crit: "20",
    speed: "104",
    move1: "Pinning Strike",
    move2: "Long Protection",
    move3: "Extended Critical Strike",
    move4: "",
    passive: "Counter",
    filename: "Rajasauru"
  },
  {
    name: "Sarcorixis",
    rarity: "2",
    hp: "3900",
    armor: "15",
    damage: "1040",
    crit: "20",
    speed: "115",
    move1: "Armor Piercing Strike",
    move2: "Lockdown Impact",
    move3: "Ferocious Strike",
    move4: "Greater Stunning Impact",
    passive: "",
    filename: "Sarniasuc",
    ing1: "Sarcosuchus",
    ing2: "Einiasuchus"
  },
  {
    name: "Sarcosuchus",
    rarity: "0",
    hp: "4200",
    armor: "10",
    damage: "1000",
    crit: "5",
    speed: "110",
    move1: "Vulnerability Strike",
    move2: "Lockdown Impact",
    move3: "",
    move4: "",
    passive: "",
    filename: "Sarcosuch"
  },
  {
    name: "Secodontosaurus",
    rarity: "2",
    hp: "3390",
    armor: "0",
    damage: "1210",
    crit: "5",
    speed: "114",
    move1: "Defense Shattering Strike",
    move2: "Defense Shattering Rampage",
    move3: "Critical Impact",
    move4: "",
    passive: "Immune",
    filename: "Secodonto"
  },
  {
    name: "Sinoceratops",
    rarity: "2",
    hp: "3750",
    armor: "25",
    damage: "1150",
    crit: "5",
    speed: "116",
    move1: "Low Stunning Strike",
    move2: "Stunning Impact",
    move3: "Instant Charge",
    move4: "",
    passive: "",
    filename: "Sinocerat"
  },
  {
    name: "Spinosaurus",
    rarity: "1",
    hp: "4050",
    armor: "0",
    damage: "1200",
    crit: "5",
    speed: "122",
    move1: "Strike",
    move2: "Wounding Strike",
    move3: "Exploit Wound",
    move4: "",
    passive: "",
    filename: "Spinosaur"
  },
  {
    name: "Spinosaurus Gen 2",
    rarity: "2",
    hp: "3900",
    armor: "0",
    damage: "1250",
    crit: "5",
    speed: "122",
    move1: "Strike",
    move2: "Lethal Wound",
    move3: "Rampage",
    move4: "",
    passive: "",
    filename: "Spinosaur2"
  },
  {
    name: "Spinotahraptor",
    rarity: "2",
    hp: "2700",
    armor: "0",
    damage: "1330",
    crit: "5",
    speed: "126",
    move1: "Strike",
    move2: "Wounding Impact",
    move3: "Distracting Rampage",
    move4: "Critical Impact",
    passive: "",
    filename: "Spinotahr",
    ing1: "Spinosaurus",
    ing2: "Utahraptor"
  },
  {
    name: "Spinotasuchus",
    rarity: "3",
    hp: "3750",
    armor: "0",
    damage: "1150",
    crit: "20",
    speed: "129",
    move1: "Strike",
    move2: "Lethal Wound",
    move3: "Wounding Impact",
    move4: "Critical Impact",
    passive: "",
    filename: "Spinotasu",
    ing1: "Kaprosuchus",
    ing2: "Spinotahraptor"
  },
  {
    name: "Stegoceratops",
    rarity: "2",
    hp: "4650",
    armor: "20",
    damage: "1300",
    crit: "5",
    speed: "115",
    move1: "Minimal Stunning Strike",
    move2: "Stunning Impact",
    move3: "Slowing Impact",
    move4: "Greater Stunning Strike",
    passive: "",
    filename: "Stegocera",
    ing1: "Triceratops",
    ing2: "Stegosaurus"
  },
  {
    name: "Stegodeus",
    rarity: "3",
    hp: "5250",
    armor: "30",
    damage: "1030",
    crit: "5",
    speed: "107",
    move1: "Superiority Strike",
    move2: "Thagomizer",
    move3: "Short Defense",
    move4: "Armor Piercing Rampage",
    passive: "",
    filename: "Stegodopa",
    ing1: "Stegosaurus",
    ing2: "Nodopatosaurus"
  },
  {
    name: "Stegosaurus",
    rarity: "0",
    hp: "4050",
    armor: "15",
    damage: "1180",
    crit: "5",
    speed: "116",
    move1: "Superiority Strike",
    move2: "Thagomizer",
    move3: "",
    move4: "",
    passive: "",
    filename: "Stegosaur"
  },
  {
    name: "Stygimoloch",
    rarity: "2",
    hp: "3690",
    armor: "0",
    damage: "1240",
    crit: "5",
    speed: "129",
    move1: "Minor Stunning Strike",
    move2: "Impact and Run",
    move3: "Instant Charge",
    move4: "",
    passive: "",
    filename: "Stygimolo"
  },
  {
    name: "Stygimoloch Gen 2",
    rarity: "0",
    hp: "3810",
    armor: "0",
    damage: "1200",
    crit: "5",
    speed: "128",
    move1: "Minimal Stunning Strike",
    move2: "Impact and Run",
    move3: "",
    move4: "",
    passive: "",
    filename: "Stygimolo2"
  },
  {
    name: "Suchomimus",
    rarity: "0",
    hp: "4500",
    armor: "0",
    damage: "1000",
    crit: "5",
    speed: "115",
    move1: "Vulnerability Strike",
    move2: "Lethal Wound",
    move3: "",
    move4: "",
    passive: "",
    filename: "Suchomimu"
  },
  {
    name: "Suchotator",
    rarity: "1",
    hp: "4800",
    armor: "0",
    damage: "1000",
    crit: "20",
    speed: "116",
    move1: "Superiority Strike",
    move2: "Lethal Wound",
    move3: "Nullifying Impact",
    move4: "Instant Cripple",
    passive: "",
    filename: "Suchotato",
    ing1: "Suchomimus",
    ing2: "Irritator Gen 2"
  },
  {
    name: "Tanycolagreus",
    rarity: "0",
    hp: "3210",
    armor: "0",
    damage: "1500",
    crit: "5",
    speed: "130",
    move1: "Armor Piercing Strike",
    move2: "Nullifying Impact",
    move3: "",
    move4: "",
    passive: "",
    filename: "Tanycolag"
  },
  {
    name: "Tarbosaurus",
    rarity: "0",
    hp: "4200",
    armor: "0",
    damage: "1600",
    crit: "40",
    speed: "104",
    move1: "Defense Shattering Strike",
    move2: "Armor Piercing Impact",
    move3: "",
    move4: "",
    passive: "",
    filename: "Tarbosaur"
  },
  {
    name: "Tenontosaurus",
    rarity: "1",
    hp: "4920",
    armor: "0",
    damage: "1050",
    crit: "5",
    speed: "111",
    move1: "Superiority Strike",
    move2: "Greater Stunning Strike",
    move3: "Distracting Strike",
    move4: "",
    passive: "",
    filename: "Tenontosa"
  },
  {
    name: "Tragodistis",
    rarity: "3",
    hp: "3600",
    armor: "40",
    damage: "900",
    crit: "5",
    speed: "124",
    move1: "Superiority Strike",
    move2: "Rampage",
    move3: "Long Invencibility",
    move4: "Greater Stunning Strike",
    passive: "Counter025",
    filename: "Paramargo",
    ing1: "Parasaurolophus",
    ing2: "Amargocephalus"
  },
  {
    name: "Triceratops",
    rarity: "1",
    hp: "3930",
    armor: "20",
    damage: "1220",
    crit: "5",
    speed: "116",
    move1: "Minor Stunning Strike",
    move2: "Stunning Impact",
    move3: "Greater Stunning Strike",
    move4: "",
    passive: "",
    filename: "Tricerato"
  },
  {
    name: "Triceratops Gen 2",
    rarity: "0",
    hp: "3600",
    armor: "10",
    damage: "1260",
    crit: "5",
    speed: "113",
    move1: "Low Stunning Strike",
    move2: "Rampage",
    move3: "",
    move4: "",
    passive: "",
    filename: "Tricerato2"
  },
  {
    name: "Trykosaurus",
    rarity: "4",
    hp: "4500",
    armor: "30",
    damage: "1660",
    crit: "20",
    speed: "102",
    move1: "Armor Piercing Strike",
    move2: "Armor Piercing Rampage",
    move3: "Defense Shattering Rampage",
    move4: "Instant Invencibility",
    passive: "Counter025",
    filename: "Trykosaur",
    ing1: "Tyrannosaurus Rex",
    ing2: "Ankyntrosaurus"
  },
  {
    name: "Tryostronix",
    rarity: "3",
    hp: "3750",
    armor: "0",
    damage: "1150",
    crit: "20",
    speed: "120",
    move1: "Armor Piercing Strike",
    move2: "Ready to Crush",
    move3: "Defense Shattering Rampage",
    move4: "Ferocious Strike",
    passive: "Immune",
    filename: "Baryostim",
    ing1: "Postimetrodon",
    ing2: "Baryonyx"
  },
  {
    name: "Tuojiangosaurus",
    rarity: "1",
    hp: "4500",
    armor: "0",
    damage: "1000",
    crit: "5",
    speed: "112",
    move1: "Superiority Strike",
    move2: "Thagomizer",
    move3: "Distracting Strike",
    move4: "",
    passive: "",
    filename: "Tuojiango"
  },
  {
    name: "Tuoramoloch",
    rarity: "4",
    hp: "4500",
    armor: "0",
    damage: "1400",
    crit: "5",
    speed: "126",
    move1: "Low Stunning Strike",
    move2: "Slowing Impact",
    move3: "Greater Stunning Rampage",
    move4: "Impact and Run",
    passive: "",
    filename: "Tuoramolo",
    ing1: "Tuojiangosaurus",
    ing2: "Paramoloch"
  },
  {
    name: "Tyrannosaurus Rex",
    rarity: "2",
    hp: "4200",
    armor: "0",
    damage: "1720",
    crit: "30",
    speed: "102",
    move1: "Armor Piercing Strike",
    move2: "Defense Shattering Impact",
    move3: "Defense Shattering Rampage",
    move4: "",
    passive: "",
    filename: "Tyrannosa"
  },
  {
    name: "Tyrannosaurus Rex Gen 2",
    rarity: "1",
    hp: "4200",
    armor: "0",
    damage: "1700",
    crit: "20",
    speed: "104",
    move1: "Armor Piercing Strike",
    move2: "Armor Piercing Impact",
    move3: "",
    move4: "",
    passive: "",
    filename: "Tyrannosa2"
  },
  {
    name: "Utahraptor",
    rarity: "1",
    hp: "2370",
    armor: "0",
    damage: "1350",
    crit: "5",
    speed: "128",
    move1: "Strike",
    move2: "Pounce",
    move3: "Critical Impact",
    move4: "",
    passive: "",
    filename: "Utahrapto"
  },
  {
    name: "Utarhinex",
    rarity: "4",
    hp: "4200",
    armor: "0",
    damage: "1230",
    crit: "5",
    speed: "126",
    move1: "Low Stunning Strike",
    move2: "Pounce",
    move3: "Critical Impact",
    move4: "Instant Charge",
    passive: "",
    filename: "Utarhinex",
    ing1: "Dracorex",
    ing2: "Utasinoraptor"
  },
  {
    name: "Utasinoraptor",
    rarity: "3",
    hp: "3000",
    armor: "15",
    damage: "1350",
    crit: "5",
    speed: "126",
    move1: "Low Stunning Strike",
    move2: "Distracting Impact",
    move3: "Critical Impact",
    move4: "Instant Charge",
    passive: "",
    filename: "Utahrhino",
    ing1: "Utahraptor",
    ing2: "Sinoceratops"
  },
  {
    name: "Velociraptor",
    rarity: "0",
    hp: "1950",
    armor: "0",
    damage: "1300",
    crit: "5",
    speed: "132",
    move1: "Strike",
    move2: "Pounce",
    move3: "",
    move4: "",
    passive: "",
    filename: "Velocirap"
  },
  {
    name: "Wuerhosaurus",
    rarity: "1",
    hp: "4500",
    armor: "15",
    damage: "1300",
    crit: "5",
    speed: "115",
    move1: "Superiority Strike",
    move2: "Thagomizer",
    move3: "Instant Cripple",
    move4: "",
    passive: "",
    filename: "Wuerhosau"
  }
];
