export const PARENTS = {
  Allosaurus: ["Allosinosaurus"],
  Sinoceratops: ["Allosinosaurus", "Utasinoraptor"],
  Amargasaurus: ["Amargocephalus", "Gigaspikasaur"],
  Euoplocephalus: ["Amargocephalus"],
  "Ankylosaurus Gen 2": ["Ankylocodon"],
  Ophiacodon: ["Ankylocodon"],
  Ankylosaurus: ["Ankyntrosaurus", "Rajakylosaurus"],
  Kentrosaurus: ["Ankyntrosaurus"],
  Dilophosaurus: ["Diloranosaurus"],
  Ouranosaurus: ["Diloranosaurus"],
  Rajakylosaurus: ["Diorajasaur"],
  Tuojiangosaurus: ["Diorajasaur", "Tuoramoloch"],
  Diplocaulus: ["Diplotator"],
  "Irritator Gen 2": ["Diplotator", "Suchotator"],
  Einiosaurus: ["Einiasuchus"],
  Nundasuchus: ["Einiasuchus", "Majundasuchus"],
  Erlikosaurus: ["Erlidominus"],
  "Indominus Rex": ["Erlidominus", "Indoraptor"],
  Nodopatosaurus: ["Gigaspikasaur", "Stegodeus"],
  Gorgosaurus: ["Gorgosuchus"],
  Kaprosuchus: ["Gorgosuchus", "Spinotasuchus"],
  Velociraptor: ["Indominus Rex", "Indoraptor"],
  "Tyrannosaurus Rex": ["Indominus Rex", "Trykosaurus"],
  Dimetrodon: ["Magnapyritor", "Postimetrodon"],
  Pyrritator: ["Magnapyritor"],
  Majungasaurus: ["Majundasuchus"],
  Megalosaurus: ["Megalosuchus"],
  Gorgosuchus: ["Megalosuchus"],
  Gallimimus: ["Monomimus"],
  Monolophosaurus: ["Monomimus", "Monostegotops"],
  Stegoceratops: ["Monostegotops"],
  Apatosaurus: ["Nodopatosaurus"],
  Nodosaurus: ["Nodopatosaurus"],
  Parasaurolophus: ["Paramoloch", "Tragodistis"],
  Stygimoloch: ["Paramoloch"],
  Postosuchus: ["Postimetrodon"],
  Pyroraptor: ["Pyrritator"],
  Irritator: ["Pyrritator"],
  Rajasaurus: ["Rajakylosaurus"],
  Sarcosuchus: ["Sarcorixis"],
  Einiasuchus: ["Sarcorixis"],
  Spinosaurus: ["Spinotahraptor"],
  Utahraptor: ["Spinotahraptor", "Utasinoraptor"],
  Spinotahraptor: ["Spinotasuchus"],
  Triceratops: ["Stegoceratops"],
  Stegosaurus: ["Stegoceratops", "Stegodeus"],
  Suchomimus: ["Suchotator"],
  Amargocephalus: ["Tragodistis"],
  Ankyntrosaurus: ["Trykosaurus"],
  Postimetrodon: ["Tryostronix"],
  Baryonyx: ["Tryostronix"],
  Paramoloch: ["Tuoramoloch"],
  Dracorex: ["Utarhinex"],
  Utasinoraptor: ["Utarhinex"]
};
